### ISSUE TITLE
Changer la langue du calendrier en français

### ISSUE THREAD

**Issue by Captiva-IT** [Captiva-IT/iTec-Template#1]
Tout est dans le titre

**Comment by bennanizak33** [comment]
c'est fait. on a ajouté un biblio de langue propre a fullCalendar

**Comment by SitrakaIT** [comment]
Bouton de contrôle en vert OK. Il reste les couleurs à diversifier.

Le mer. 16 oct. 2019 à 11:53, bennanizak33 <notifications@github.com> a
écrit :
