### ISSUE TITLE
href icône pdf

### ISSUE THREAD

**Issue by Captiva-IT** [Captiva-IT/iTec-Template#4]
Mettre le user Guide iTec dans la solution
Pointer dessus le href de l'icône pdf du tableau

**Comment by Captiva-IT** [comment]
Des news de cette demande ? @bennanizak33

**Comment by bennanizak33** [comment]
on vient de terminée les modals. tu peux les tester.

je vais commencer sur le pdf.
________________________________

**Comment by bennanizak33** [comment]
c'est bon j'ai fais un premier commit. il a l'air de marché il faut juste patienté pour le chargement du document.
